config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tatuadors
  resources :tattoos

  root to:'tattoos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tattoo.rb
class Tattoo < ApplicationRecord
     mount_uploader :avatar, AvatarUploader
     belongs_to:tatuador
end

app/controllers/tattoos_controller.rb
class TattoosController < ApplicationController
  before_action :set_tattoo, only: [:show, :edit, :update, :destroy]

  # GET /tattoos
  # GET /tattoos.json
  def index
    @tattoos = Tattoo.page(params[:page]).per(2)
  end

  # GET /tattoos/1
  # GET /tattoos/1.json
  def show
  end

  # GET /tattoos/new
  def new
    if current_user.role == 'Editor'
      @tattoo = Tattoo.new
    else 
      redirect_to tattoos_url
    end
    @tatuadors = Tatuador.all
  end

  # GET /tattoos/1/edit
  def edit
  end

  # POST /tattoos
  # POST /tattoos.json
  def create
    @tattoo_guy = Tatuador.find(1)
    @tattoo = Tattoo.new(tattoo_params)
    respond_to do |format|
      if @tattoo.save
        format.html { redirect_to @tattoo, notice: 'Tattoo was successfully created.' }
        format.json { render :show, status: :created, location: @tattoo }
      else
        format.html { render :new }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tattoos/1
  # PATCH/PUT /tattoos/1.json
  def update
    respond_to do |format|
      if @tattoo.update(tattoo_params)
        format.html { redirect_to @tattoo, notice: 'Tattoo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tattoo }
      else
        format.html { render :edit }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tattoos/1
  # DELETE /tattoos/1.json
  def destroy
    if current_user.role == 'Editor' 
      @tattoo.destroy
    else
      redirect_to tattoo_url
    end
    
    respond_to do |format|
      format.html { redirect_to tattoos_url, notice: 'Tattoo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tattoo
      @tattoo = Tattoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tattoo_params
      params.require(:tattoo).permit(:descripcion, :avatar, :tatuador_id)
    end
end

app/helpers/tattoos_helper.rb
module TattoosHelper
end

app/views/tattoos/_form.html.erb
<%= form_for(tattoo) do |f| %>
  <% if tattoo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(tattoo.errors.count, "error") %> prohibited this tattoo from being saved:</h2>

      <ul>
        <% tattoo.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <div class="container">
        <div class="card-panel">
          <div class="field">
            <%= f.label :descripcion %>
              <%= f.text_field :descripcion %>
          </div>

          <div class="field">
            <%= f.collection_select:tatuador_id, Tatuador.order(:nombre), :id, :nombre, include_blank:false, :class=>'browser-default' %>
          </div>

          <div class="field">
            <%= f.file_field :avatar %>
          </div>



          <div class="actions waves-effect blue darken btn">
            <%= f.submit %>
          </div>
        </div>
      </div>

      <% end %>

app/views/tattoos/edit.html.erb
<h1 class="center">Editing Tattoo</h1>

<%= render 'form', tattoo: @tattoo %>

    <div class="center-align">
        <%= link_to 'Show', @tattoo, :class=>'waves-effect blue darken btn' %> |
        <%= link_to 'Back', tattoos_path, :class=>'waves-effect blue darken btn' %>
    </div>

app/views/tattoos/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<h1 class="center">Tattoos</h1>
<div class="container">
  <div class="card-panel">
    <div class="right-align">
      <% if current_user.role == 'Editor'%>
        <%= link_to 'New', new_tattoo_path, :class=>'btn-floating btn-large green accent-4' %>
        <%= link_to 'Artist', tatuadors_path, :class=>'btn-floating btn-large blue darken' %>
      <% end %>
    </div>
    <table class="highlight">
      <thead>
        <tr>
          <th>Imagen</th>
          <th>Descripcion</th>
          <th>Artista</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tattoos.each do |tattoo| %>
          <tr>
            <td>
              <%= image_tag tattoo.avatar, :class=>'tattooimg' %>
            </td>
            <td>
              <%= tattoo.descripcion %>
            </td>
            <td>
              <%= Tatuador.find(tattoo.tatuador_id).nombre %>
            </td>

            <td>
              <%= link_to 'Show', tattoo, :class=>'waves-effect blue darken btn'%>
              <% if current_user.role == 'Editor'%>
                <%= link_to 'Edit', edit_tattoo_path(tattoo), :class=>'waves-effect green accent-4 btn' %>
                <%= link_to 'Destroy', tattoo, method: :delete, data: { confirm: 'Are you sure?' }, :class=>'waves-effect red darken btn' %>
              <% end %>
            </td>
          </tr>
          <% end %>
      </tbody>
      <%= paginate @tattoos %>
    </table>


  </div>
  
</div>


<br>

app/views/tattoos/new.html.erb
<h1 class="center">New Tattoo</h1>

<%= render 'form', tattoo: @tattoo %>

<%= link_to 'Back', tattoos_path, :class=>'waves-effect blue darken btn' %>

app/views/tattoos/show.html.erb
<p id="notice">
  <%= notice %>
</p>


<div class="container">
  <div class="card-panel">
    <div class="center">
      <%= image_tag @tattoo.avatar, :class=>'tattooshow' %>
    </div>

    <p>
      <strong>Descripcion:</strong>
      <%= @tattoo.descripcion %>
    </p>
    <p>
      <strong>Artista:</strong>
      <%= Tatuador.find(@tattoo.tatuador_id).nombre %>
    </p>

  </div>
</div>




<p>

</p>
<div class="center-align">
<% if current_user.role == 'Editor'%>
  <%= link_to 'Edit', edit_tattoo_path(@tattoo), :class=>'waves-effect blue darken btn' %> |
<% end %>
  <%= link_to 'Back', tattoos_path, :class=>'waves-effect blue darken btn' %>
</div>