config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tatuadors
  resources :tattoos

  root to:'tattoos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tatuador.rb
class Tatuador < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    has_many:tattoos
end

app/controllers/tatuadors_controller.rb
class TatuadorsController < ApplicationController
  before_action :set_tatuador, only: [:show, :edit, :update, :destroy]

  # GET /tatuadors
  # GET /tatuadors.json
  def index
    @tatuadors = Tatuador.all
  end

  # GET /tatuadors/1
  # GET /tatuadors/1.json
  def show

  end

  # GET /tatuadors/new
  def new
    if current_user.role == 'Editor'
      @tatuador = Tatuador.new
    else 
      redirect_to tattoos_url
    end
  end

  # GET /tatuadors/1/edit
  def edit
  end

  # POST /tatuadors
  # POST /tatuadors.json
  def create
    @tatuador = Tatuador.new(tatuador_params)

    respond_to do |format|
      if @tatuador.save
        format.html { redirect_to @tatuador, notice: 'Tatuador was successfully created.' }
        format.json { render :show, status: :created, location: @tatuador }
      else
        format.html { render :new }
        format.json { render json: @tatuador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tatuadors/1
  # PATCH/PUT /tatuadors/1.json
  def update
    respond_to do |format|
      if @tatuador.update(tatuador_params)
        format.html { redirect_to @tatuador, notice: 'Tatuador was successfully updated.' }
        format.json { render :show, status: :ok, location: @tatuador }
      else
        format.html { render :edit }
        format.json { render json: @tatuador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tatuadors/1
  # DELETE /tatuadors/1.json
  def destroy
    @tatuador.destroy
    respond_to do |format|
      format.html { redirect_to tatuadors_url, notice: 'Tatuador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tatuador
      @tatuador = Tatuador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tatuador_params
      params.require(:tatuador).permit(:nombre, :avatar)
    end
end

app/helpers/tatuadors_helper.rb
module TatuadorsHelper
end

app/views/tatuadors/_form.html.erb
<%= form_for(tatuador) do |f| %>
  <% if tatuador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tatuador.errors.count, "error") %> prohibited this tatuador from being saved:</h2>

      <ul>
      <% tatuador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="card-panel">
    <div class="field">
      <%= f.label :nombre %>
      <%= f.text_field :nombre %>
    </div>

    <div class="actions waves-effect blue darken btn">
      <%= f.submit %>
    </div>
  </div>
</div>
  
<% end %>

app/views/tatuadors/edit.html.erb
<h1>Editing Tatuador</h1>

<%= render 'form', tatuador: @tatuador %>

<%= link_to 'Show', @tatuador %> |
<%= link_to 'Back', tatuadors_path %>

app/views/tatuadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Tatuadors</h1>
<div class="container">
    <div class="card-panel">
      <table class="highlight centered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th colspan="3">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @tatuadors.each do |tatuador| %>
            <tr>
              <td><%= tatuador.nombre %></td>
              <td><%= link_to 'Show', tatuador,:class=>'waves-effect blue darken btn' %>
              <%= link_to 'Edit', edit_tatuador_path(tatuador),:class=>'waves-effect green accent-4 btn' %>
              <%= link_to 'Destroy', tatuador, method: :delete, data: { confirm: 'Are you sure?' },:class=>'waves-effect red darken btn' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>


<br>
<div class="container">
  <div class="right">
    <%= link_to 'New Tatuador', new_tatuador_path,:class=>'waves-effect green accent-4 btn' %>
  </div>
</div>

app/views/tatuadors/new.html.erb
<h1 class="center">New Tatuador</h1>

<%= render 'form', tatuador: @tatuador %>

<%= link_to 'Back', tatuadors_path %>

app/views/tatuadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tatuador.nombre %>
</p>

<%= link_to 'Edit', edit_tatuador_path(@tatuador) %> |
<%= link_to 'Back', tatuadors_path %>